spring.application.name=library-management
server.port=${PORT:8082}

# --- Clever Cloud MySQL Configuration ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate Properties ---
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=always

# Enable Eureka registration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:https://eureka-service-s7wp.onrender.com/eureka/}

# Cloud-friendly registration
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.instance.non-secure-port=${PORT:8082}

# --- Hikari CP connection pool configuration for Clever Cloud ---
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000

# --- JWT SECURITY CONFIGURATION ---
college.app.jwtSecret=${JWT_SECRET}

management.endpoints.web.exposure.include=health
